# Generated by Django 4.1.3 on 2023-07-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangazonapi', '0002_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='http://dummyimage.com/159x100.png/cc0000/ffffff', max_length=300),
            preserve_default=False,
        ),
    ]
